# Generated by Django 2.0.4 on 2018-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_when_edit_category',
            new_name='email_when_edit_list',
        ),
    ]
