# Generated by Django 2.0.4 on 2018-04-18 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0003_auto_20180418_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('entry_by', 'category', 'url')},
        ),
    ]
