# Generated by Django 2.0.4 on 2018-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20180418_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_global',
            field=models.IntegerField(choices=[(1, 'GLOBAL'), (2, 'PRIVATE'), (3, 'WAS PRIVATE NOW GLOBAL'), (4, 'WAS GLOBAL NOW PRIVATE'), (5, 'SHARED WITH FRIENDS')], default=2),
        ),
    ]
