# Generated by Django 2.0.4 on 2018-06-25 14:10

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_category_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(validators=[common.validators.url_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
    ]
