# Generated by Django 2.0.4 on 2018-07-25 19:59

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0012_auto_20180625_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=common.fields.TimestampImageField(blank=True, null=True, upload_to='bookmark/categories'),
        ),
    ]
